# Generated by Django 4.2.2 on 2023-06-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('subregion', models.CharField(max_length=255)),
                ('capital', models.CharField(max_length=255)),
                ('independent', models.BooleanField()),
                ('population', models.IntegerField()),
                ('area', models.FloatField()),
                ('google_maps', models.URLField()),
                ('currency_name', models.CharField(max_length=255)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=255)),
                ('flag_png', models.URLField()),
                ('flag_alt', models.TextField()),
            ],
        ),
    ]
