# Generated by Django 4.2.2 on 2023-06-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='currency_name',
            new_name='currencies',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='language',
            new_name='languages',
        ),
        migrations.RemoveField(
            model_name='country',
            name='currency_symbol',
        ),
    ]
