# Generated by Django 4.2.2 on 2023-06-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_currency_name_country_currencies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='country',
            name='common_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='country',
            name='currencies',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='country',
            name='official_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='country',
            name='subregion',
            field=models.CharField(max_length=1000),
        ),
    ]
