# Generated by Django 4.2.2 on 2023-06-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_country_capital_alter_country_common_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='independent',
            field=models.CharField(max_length=1000),
        ),
    ]
